# Site settings
title: Meu Site
description: Descrição do meu site
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
permalink: pretty

# Theme settings
theme: jekyll-theme-midnight

# Collections
collections:
  docs:
    output: true
    permalink: /docs/:path/

# Default front matter
defaults:
  -
    scope:
      path: ""
      type: "docs"
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore 